# Copyright Contributors to the Open Cluster Management project

{{- if .Values.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "application-manager.fullname" . }}-predelete"
  namespace: {{ .Release.Namespace }}
  labels:
    open-cluster-management.io/addon-pre-delete: ""
    app: {{ template "application-manager.name" . }}
    chart: {{ template "application-manager.chart" . }}
    component: "application-manager"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ template "application-manager.fullname" . }}-predelete"
      labels:
        app: {{ template "application-manager.name" . }}
        component: "application-manager"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        chart: {{ template "application-manager.chart" . }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ template "application-manager.fullname" . }}
      containers:
      - name: pre-delete-job
        image: "{{ .Values.global.imageOverrides.multicluster_operators_subscription }}"
        imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
        command: ["uninstall-crd"]
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: "{{ .Values.global.imagePullSecret }}"
      {{- end }}
{{- end }}
