# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "application-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "application-manager.name" . }}
    chart: {{ template "application-manager.chart" . }}
    component: "application-manager"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
