kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .ManagedClusterName }}-addon-application-manager"
  namespace: "{{ .ManagedClusterName }}"
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "{{ .Group }}"
roleRef:
  kind: ClusterRole
  name: open-cluster-management:addons:application-manager
  apiGroup: rbac.authorization.k8s.io
